# Generated by Django 4.2.8 on 2024-05-10 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asociacion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('ubicacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marca_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_vehiculo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Razon_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social_operador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tipo_de_tramite', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('botic', models.CharField(max_length=100)),
                ('conductor', models.CharField(max_length=100)),
                ('fecha_ve', models.DateField()),
                ('fecha_vvv', models.DateField()),
                ('hora_ve', models.TimeField()),
                ('categoria', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('tipo_de_vehiculo', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('chasis', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
                ('tipo_tarjeta', models.CharField(max_length=100)),
                ('validez', models.CharField(max_length=100)),
                ('gestion', models.CharField(max_length=100)),
                ('rutas', models.TextField()),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.afiliado')),
                ('marca_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.marca_vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tramite', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('solicitante', models.CharField(max_length=255)),
                ('num_fojas', models.IntegerField()),
                ('fecha_entrega_form_obs', models.DateField()),
                ('estado', models.CharField(choices=[('Ingresado', 'Ingresado'), ('Anulado', 'Anulado'), ('Entregado', 'Entregado'), ('Proceso', 'Proceso')], max_length=50)),
                ('comentario', models.TextField()),
                ('tipo_de_tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tipo_tramite')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdf_tarjetas_operacion/')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones_vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacio', models.TextField()),
                ('fecha_obs', models.DateField()),
                ('hora_obs', models.TimeField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones_afiliados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacio', models.TextField()),
                ('fecha_obs', models.DateField()),
                ('hora_obs', models.TimeField()),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.afiliado')),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacio', models.TextField()),
                ('fecha_obs', models.DateField()),
                ('hora_obs', models.TimeField()),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tramite')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tramite')),
            ],
        ),
        migrations.AddField(
            model_name='afiliado',
            name='razon_social_operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.razon_social'),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tramite'),
        ),
    ]
