# Generated by Django 4.2.8 on 2024-02-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='TipoTramites',
        ),
        migrations.DeleteModel(
            name='Tramite',
        ),
    ]
