# Generated by Django 4.2.8 on 2024-02-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_tramite_num_tramite_alter_tramite_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='id',
            field=models.BigAutoField(default=1500, primary_key=True, serialize=False),
        ),
    ]
