# Generated by Django 4.2.8 on 2024-02-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_tramite_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='tipo_tramite',
        ),
        migrations.DeleteModel(
            name='TipoTramites',
        ),
    ]
