# Generated by Django 4.2.8 on 2024-02-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_documento_tipo_tramite_delete_tipotramites'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='tipo_de_tramite',
            field=models.CharField(default='afiliaciion', max_length=255),
            preserve_default=False,
        ),
    ]
