# Generated by Django 4.2.8 on 2024-02-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_tramite_tipo_de_tramite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='estado',
            field=models.CharField(choices=[('Ingresado', 'Ingresado'), ('Anulado', 'Anulado'), ('Entregado', 'Entregado'), ('Proceso', 'Proceso')], max_length=50),
        ),
    ]
