# Generated by Django 4.2.8 on 2024-02-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_tramite_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tipo_de_tramite', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='tramite',
            name='tipo_de_tramite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tipo_tramite'),
        ),
    ]
