# Generated by Django 4.2.8 on 2024-02-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_tipo_tramite_alter_tramite_tipo_de_tramite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='ruta_archivo',
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(null=True, upload_to='documentos/'),
        ),
    ]
